version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_restapi-dev:/var/lib/postgresql/data

  migrate:
    container_name: migrate
    image: migrate/migrate:v4.16.2
    command: >
      -source 'file:///migrations'
      -database 'postgresql://postgres:yourpassword@postgres:5432/${DB_NAME}?sslmode=disable' up
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations:ro

volumes:
  postgres_restapi-dev:
